### ISSUE TITLE
New images needed

### ISSUE THREAD

**Issue by dc34** [Pineapple-Creative-UK/tyre-label-generator#4]
Hi, I am using and loving your labelling but I have need some images which you don't have db_68.png and db_65.png 

Is it possible for you to issue a template where I could create any missing images
Many Thanks John

**Comment by OdinsHat** [comment]
Apologies for the 5 year wait. I'm speaking to the designer of the original file to see if he can provide the PSD. Once I get it I'll update the package with fresh images re-optimised for the latest web standards. Maybe offer the ability to have different image types (PNG, SVG, WEBP).

If the tyre label design has changed or the designer doesn't get in touch I'll re-create the library using new designs taken from another place.

**Comment by OdinsHat** [comment]
I'm closing this bug as I've now included the original EPS file which you can use to create as many alternative images as you wish
